# Choose from ["NVIDIA_GPU", "CAMBRICON_MLU", "ASCEND_NPU", 
#              "METAX_GPU", "MOORE_GPU", "SUGON_DCU", "ILLUVATAR_GPU"]
export PLATFORM_ENV="ASCEND_NPU"

# 昇腾平台：将 ASCEND_RT_VISIBLE_DEVICES 映射到 CUDA_VISIBLE_DEVICES
# 使基于 CUDA_VISIBLE_DEVICES 的脚本和 usercustomize.py 钩子能正确工作
if [ -n "$ASCEND_RT_VISIBLE_DEVICES" ] && [ -z "$CUDA_VISIBLE_DEVICES" ]; then
    export CUDA_VISIBLE_DEVICES="$ASCEND_RT_VISIBLE_DEVICES"
fi
